version: '3'

services:
  event-manager:
    container_name: event-manager
    image: bertoluccialan/event-manager
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3000
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:alpine'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=event_manager,event_manager_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 63780:63780
