name: Complete workflow

on:
  push:
    branches:
      - master
      - develop
    pull_request:
      branches:
        - master
        - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run all tests
        timeout-minutes: 1
        run: yarn test
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: ./ghaction_script.sh
